### ISSUE TITLE
Issue Tracker, Display of a Thousand Plugs

### ISSUE THREAD

**Issue by ChiriVulpes** [ChiriVulpes/deepsight.gg#15]
- [x] Enhanced perks displaying on adept collections rolls
- [x] Invalid perks displaying on collections rolls
- [x] Dead messenger drop with weird plugs in item view
- [x] Adept raid weapons with "trait locked" and "enhancement"
- [x] #12 
- [ ] Fix enhanced intrisic tooltips not displaying the stat they increase
- [ ] Harmonic reserves not displaying
- [ ] Empty trait slot in dead messenger
- [ ] Craftable origin on DSC weapons?
- [ ] Shiver Quiver exotic catalyst in traits category
- [ ] Unequipped origin traits not displaying
- [ ] normal frame in exotic intrinsic category?

**Comment by ChiriVulpes** [comment]
![image](https://github.com/ChiriVulpes/deepsight.gg/assets/6081834/e0476463-88bb-4e65-b944-a5ab60b883ad)
